# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  buildApk:
#    working_directory: code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
      - run:
          name: Build Apk
          command: |
            ls
            ./gradlew assembleDebug
            pwd
            nowTime=$(date +"%Y%m%d%H%M%S")
            outName="${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BUILD_NUM}_${nowTime}.apk"
            echo "文件的输出名字是：${outName}"
            apkPath="app/build/outputs/apk/debug/app-debug.apk"
            destPath="$outName"
            echo "apk 的原始地址是：${apkPath}， apk 的目标地址是：${destPath}"
            sudo mv ${apkPath} ${destPath}
            APK_PATH="$CIRCLE_WORKING_DIRECTORY/$destPath"
            ls
            echo $APK_PATH>APK_NAME.txt
      - run:
          name: 上传到蒲公英
          command: |
            apkName=head -1 APK_NAME.txt
            echo "保存的路径是：$apkName"
            curl -F "file=@$apkName" \
            -F "uKey=0d4628d290cecf6730f5df1949e1515c" \
            -F "_api_key=808950acaea5f1c000852ad42e87fe0e" \
            http://www.pgyer.com/apiv1/app/upload

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Run Tests
#          command: ./gradlew lint test

